### PR TITLE
Notify after Jenkins lisk-service-nightly job fails

### LINKED ISSUE #1329: Notify after Jenkins lisk-service-nightly job fails
### Description

Task lisk-service-nightly often fails without any information. 

### Motivation

Currently, the task has no notifications about any problems. The task needs alerts to better monitor issues.

### PR DESCRIPTION
**Pull request by paveleu**
### What was the problem?
This PR resolves #1329

### How was it solved?
The Jenkinsfile of lisk-service-nightly has been modified.

### How was it tested?
After merging to the development branch, if the lisk-service-nightly task fails, an e-mail will be sent to service@lightcurve.io

### CODE REVIEW

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
@paveleu I do not see the group (service@lightcurve.io) defined in https://groups.google.com/u/1/all-groups. Could you please double check?

**Comment by paveleu** [comment]
> @paveleu I do not see the group ([service@lightcurve.io](mailto:service@lightcurve.io)) defined in https://groups.google.com/u/1/all-groups. Could you please double check?

Destination email has been corrected and set to the newly created group.

**Review by sameersubudhi — APPROVED** [review]
Thank you @paveleu 🙇

**Review by Nazgolze — APPROVED** [review]

**Review by nagdahimanshu — APPROVED** [review]
Looks good 👍

**Pull request merged**
